### ISSUE TITLE
Windows: No environment variable added for PDK installation using cmd.exe

### ISSUE THREAD

**Issue by bloodmc** [puppetlabs/pdk-vanagon#165]
PDK - 1.6.1.0-x64
OS - Windows 10

After installing PDK and running `cmd.exe`, pdk is an unrecognized command. Adding 
`C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.4.4\bin` solves the issue.

**Comment by scotje** [comment]
PDK's Windows interface is only implemented for PowerShell, we deliberately do not manipulate the cmd.exe PATH environment.
